version: '2'
services:
  spingularchatsprint1-app:
    image: spingularchatsprint1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spingularchatsprint1-postgresql:5432/spingularchatsprint1
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  spingularchatsprint1-postgresql:
    extends:
      file: postgresql.yml
      service: spingularchatsprint1-postgresql
